# Your Name or Company
title: christy frink

# Description of your website. This is used for social sharing.
description: Hi, I'm Christy 
# A brief blurb about yourself
content: ğŸ“ <strong><mark>baltimore, maryland</mark></strong><br>
  edtech product manager and chaotic good, equal parts crochet hooks and powertools. she/her/y'all. some projects i have my hands in ğŸ‘‡<br>
  ğŸ–¤ <a href="https://www.unmgmt.org" target="_blank">unmanageable</a><br>
  ğŸ–¤ <a href="https://www.chatterbird.org" target="_blank">chatterbird</a><br>
  ğŸ–¤ <a href="https://www.highzerofoundation.org" target="_blank">high zero foundation</a><br>
  ğŸ–¤ <a href="https://www.baltimorefordemocracy.org/" target="_blank">baltimore for democracy</a>


# Add your social links
social:
  - platform: linkedin
    url: https://www.linkedin.com/in/christyfrink/
  - platform: bluesky
    url: https://bsky.app/profile/christyfrink.com
  - platform: cat pics
    url: https://www.instagram.com/christyfrink/

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
